# Generated by Django 3.2.22 on 2023-12-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20231225_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
    ]
