# Generated by Django 3.2.22 on 2023-12-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_choices_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
